# Generated by Django 4.2.14 on 2024-07-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(1, 'Published'), (0, 'Draft')], default=0),
        ),
    ]
