# Generated by Django 4.2.14 on 2024-07-17 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='about_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='about_title',
            new_name='title',
        ),
    ]
